// create enum's
const PLAYER_MOVEMENTS = {
  x: 160,
  y: 300,
};

const SHAPE_DELAY = 2500;

const TRIANGULO = "Triangulo";
const CUADRADO = "Cuadrado";
const ROMBO = "Rombo";

const SHAPES = [TRIANGULO, CUADRADO, ROMBO];
const POINTS_PERCENTAGE= "value";
const POINTS_PERCENTAGE_VALUE_START = 1;

export { PLAYER_MOVEMENTS, SHAPE_DELAY, SHAPES, TRIANGULO, CUADRADO, ROMBO, POINTS_PERCENTAGE, POINTS_PERCENTAGE_VALUE_START };
